Add dynamic select for service name and entity [sc-163505]
dataiku/dss-plugin-sap-odata pull request #11
Opened 2023-12-12 15:37 UTC by alexbourret

Story details: https://app.shortcut.com/dataiku/story/163505

2024-01-31 10:38 UTC, Alexlandeau requested changes
Plugin works fine, a few nitpicks / open questions on syntax though

2024-01-31 13:21 UTC, alexbourret commented on python-lib/odata_client.py
> +        entity = entity or ""
Fixed in [363fe9a](https://github.com/dataiku/dss-plugin-sap-odata/pull/11/commits/363fe9a3a6b0a4fd0bb74f0574c09cbbe5cf00b2)

2024-01-31 13:21 UTC, alexbourret commented on python-lib/odata_common.py
> +    odata_list_title = config.get("odata_list_selector")
Fixed in [363fe9a](https://github.com/dataiku/dss-plugin-sap-odata/pull/11/commits/363fe9a3a6b0a4fd0bb74f0574c09cbbe5cf00b2)

2024-01-31 13:21 UTC, alexbourret commented on python-lib/odata_common.py
> +            for choice_key in choices:
Fixed in [363fe9a](https://github.com/dataiku/dss-plugin-sap-odata/pull/11/commits/363fe9a3a6b0a4fd0bb74f0574c09cbbe5cf00b2)

2024-02-01 14:44 UTC, Alexlandeau approved these changes
LGTM !

2024-02-01 15:48 UTC, merged